GET http://localhost:8888/api/customers

###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/3

###

GET http://localhost:8888/api/timebills/2

###

POST http://localhost:8888/api/timebills
Content-Type: application/json

{
  "hoursWorked": 3.0,
  "rate": 5000.00,
  "date": "2024-05-05",
  "work": "I did a thing...",
  "customerId": 1,
  "employeeId":1
}