GET http://localhost:8888/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFsdmluIiwic3ViIjoiQWx2aW4iLCJqdGkiOiI1YjM1MTVlMSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjMyMzY4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6MCIsImh0dHA6Ly9sb2NhbGhvc3Q6ODg4OCJdLCJuYmYiOjE3MjU2NTg3NjcsImV4cCI6MTczMzUyMTE2NywiaWF0IjoxNzI1NjU4NzY4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.wawCK_A861g1cFqw11U-7yrWOtvUNk_39TqKCgEHlgM

###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/3

###

GET http://localhost:8888/api/timebills/2

###

POST http://localhost:8888/api/timebills
Content-Type: application/json

{
  "hoursWorked": 3.0,
  "rate": 225.00,
  "date": "2024-05-05",
  "work": "I did a thing...",
  "customerId": 1,
  "employeeId":1
}

###
GET http://localhost:8888/api/customers/1/timebills

###
GET http://localhost:8888/api/customers/1/timebills/10