GET http://localhost:8888/api/customers
Authorization: Bearer CfDJ8FNl7_BEFLxMj1laFgISwGUQtaZC01bScRB-5nT-rgl3gT8URhELugGMCTxPVbsAJev8G8Cmwh9k5voSPKV9gnZh31vZ0eGYxIsRZGLHWR9r0Xb4LVTRR2GsA0rinTjEE1Ta5q4nYBXRqQI_vWzj985ktcrc1mZ7jdHCOZqWH4SmeS7p1Ckh_Bd3NZBrzLpiuaB24MacdvCd4a3_ym1sgLm2_GD_nKiIMGGdAddPyXacHGpyWbDyvXXNHV2_j-RI_DY-9AzCdAU14r8BvOMtO0O2b0xEVmG1ujFX50h9Y4crVQAKH141QtxL8CQCUxwIDF09UafTpT1WAxRSbMqZ9zNcP4-BllFqkCMuC0OdaWue1PeQEmZj-Rx7XKCjpRJAWuQhVKtOoxcZECqa0Q1sI-_36wR_m27_KgKnML5AXFBSkW-3TXRbs7j0udY6j_TGhgGQsa9D73smqPKqFHYcTeeqv0wt1sH8rcRSlp5W7LwExR-hY7193F8Spz6bbYoygZ1a3DUwJsACZJa4RYJnOK1w4eD4lMtrRiMGQi_96ZPlZ5ppHeVtQPBbqYfBp3Op0C2kfj1TO8IOR3zJFYIjorxLBB7shFyKJ8fs2vEyADFaMn0gCDfF7jY19hTzi3-GjA9ktoEa1anmmX7Xa_X-tPQobwSrRdS733k-ghdKfFd59mR4LrWUh0FzCCkvkqLE-kbHRD4BFKK3ICqGEdkFHmY
###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/3

###

GET http://localhost:8888/api/timebills/2

###
GET http://localhost:8888/api/customers/1/timebills

###
GET http://localhost:8888/api/timebills/2
Authorization: Bearer CfDJ8FNl7_BEFLxMj1laFgISwGV6vJ0bsoQyE2yB7xgs_dcLosWHHWpQnAoh9UZfreBLiqHzmMQpSmc7QNdxa78Dyyle8n-o6ple6UFDNAahS_0S_9fiDNWSgCbOyi6RhCBUknarY9tOXXg1GqwjD2b21875k4ULmCEI1iwYyQ9rklEHrzlEFj-2O03-zJbMckhPT4hXSsb3LlVKTRs2GSxyC8pGrogOuUVe85ga9BU6tTbj42Zf3_uKXyOBwf7u5s7_5RK1f76Z0aAns6lS3GX_R9yGW71-tXznyiSOp5YeYNql66K17AldSV72YGDTlIaNYAqkbN6ZbclKypXEd0zFS-1_6CwImHwSof5gotWPo41pY4DTfWiN606LUbIDIvN8Kv0GtI466ejpD4VobDJ94-nxNDIsvlp3BRRy3xrhuLrBAHWZiisDk0ZGCYyNNVP-gd8ShwBEJXmu-uTAlvJJfjDICsAyhapIeMNcy-CCVRlkIZNz7iUp3JywYbgigvx7LeHNUuZJBLBjH_TmL4Xgw9Hvae46f5FrWpCW4PyZjPPbL70Zl2UhkEKxyztBQJYW37GW1FPKeNukn3LbuDUdOrGUHKeCfYlaMYKezUArXPAiGIx5T6JxP2SIJMoJAhwzhJPpgMfP1TfCSR3Fy_Y76D9KV8faVydFysrbqSc5U4VMBzdZ4d7nCb5dHDx448S9RAy56evEjW8zpvFJERQ5arY

###
GET http://localhost:8888/api/employees

###

POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
  "email": "alvin.ramirez48@gmail.com",
  "password": "Test2024*"
}